version: '3'

services:

  db:
    image: 'postgres:15.3-alpine'
    restart: always
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - 'POSTGRES_USER=nurs'
      - 'POSTGRES_DB=kino'
      - 'POSTGRES_PASSWORD=nurs'